#!/usr/bin/env bash

# Disable the includes checking in spellcheck:
# shellcheck disable=SC1091

# TASK=${1}
PATH=${2}
CMD=${3}
IMAGE=${4:-aroq/variant}
export IMAGE

PREFIX=".toolbox"

# Load environment variables from .env file
if [[ -f ".env" ]]; then
  source ".env"
fi

# Load environment variables from  local git-ignored .env.local file
if [[ -f ".env.local" ]]; then
  source ".env.local"
fi

# Load environment variables from .env file
if [[ -f ".env.k6" ]]; then
  source ".env.k6"
fi

# Load environment variables from  local git-ignored .env.local file
if [[ -f ".env.k6.local" ]]; then
  source ".env.k6.local"
fi

if [[ -f ${PATH}/${CMD} ]]; then
  TOOL_PATH="${PATH}/${CMD}"
else
  TOOL_PATH="${PREFIX}/${PATH}/${CMD}"
fi

# Remove the first 4 arguments
shift; shift; shift; shift;

# Replace "=" by " " in args to make sure makefile is not trying to process them
ARGS=$(echo "$*" | tr '=' ' ')

eval "make -s ${TOOL_PATH} -- ${ARGS}"

