#!/usr/bin/env bash

# Disable the includes checking in spellcheck:
# shellcheck disable=SC1091

CMD=${1}
IMAGE=${IMAGE:-$2}
export IMAGE
PREFIX=${PREFIX:-.toolbox}

# echo "CMD: ${CMD}"

# echo "TOOLBOX_RUN: ${TOOLBOX_RUN}"
# echo "TOOLBOX_RUN_DIRECT before: ${TOOLBOX_RUN_DIRECT}"

if [ -z ${TOOLBOX_RUN+x} ] && [ -z ${TOOLBOX_RUN_DIRECT+x} ]; then
  # echo "TOOLBOX_RUN & TOOLBOX_RUN_DIRECT are not provided"
  if [ -f /.dockerenv ]; then
    echo "Inside docker already, setting TOOLBOX_RUN_DIRECT to false"
  fi
  export TOOLBOX_RUN=false
  export TOOLBOX_RUN_DIRECT=false
fi

# echo "TOOLBOX_RUN_DIRECT after: ${TOOLBOX_RUN_DIRECT}"

# Load environment variables from .env file
if [[ -f ".env" ]]; then
  source ".env"
fi

# Load environment variables from  local git-ignored .env.local file
if [[ -f ".env.local" ]]; then
  source ".env.local"
fi

# Load environment variables from .env file
if [[ -f ".env.k6" ]]; then
  source ".env.k6"
fi

# Load environment variables from  local git-ignored .env.local file
if [[ -f ".env.k6.local" ]]; then
  source ".env.k6.local"
fi

if [[ -f "${CMD}" ]]; then
  TOOL_PATH="${CMD}"
else
  TOOL_PATH="${PREFIX}/${CMD}"
fi

# Remove the first 2 arguments
shift
shift

export TOOLBOX_RUN=true

# Replace "=" by " " in args to make sure makefile is not trying to process them
ARGS=$(echo "$*" | tr '=' ' ')
eval "make ${TOOL_PATH} -- ${ARGS}"
