deps:
  toolbox: github.com/aroq/toolbox

from:
# Make sure you have proper deps dir here
- toolbox/.toolbox/deps/toolbox/config/toolbox.settings.yaml
tools:
  test:
    from:
    - config.libraries
    cmd: test_variant

