config:
  libraries:
    params:
      prefix: .toolbox
      tools_dir: tools
      image: aroq/toolbox
      env:
        TOOLBOX_RUN_VARIANT: true
        TOOLBOX_DOCKER_SSH_FORWARD: false
    toolbox:
      params:
        destination: toolbox
        source: github.com/aroq/toolbox//tools
      commands:
        toolbox:
          params:
            cmd: toolbox/toolbox
        template:
          params:
            cmd: toolbox/template
        uniconf:
          params:
            cmd: toolbox/uniconf
    cicd:
      params:
        destination: cicd
        source: github.com/aroq/toolbox-cicd
        image: aroq/variant-cicd
        env:
          TOOLBOX_DOCKER_SSH_FORWARD: true
      commands:
        release:
          build:
            params:
              cmd: release/build/build
          deploy:
            params:
              cmd: release/deploy

  profiles:
    aws:
      params:
        env:
          AWS_ACCESS_KEY_ID:
          AWS_SECRET_ACCESS_KEY:
          AWS_DEFAULT_REGION:
          AWS_SESSION_TOKEN:
          AWS_SECURITY_TOKEN:

tools:
  toolbox:
    from: config.libraries.toolbox.commands.toolbox
  template:
    from: config.libraries.toolbox.commands.template
  uniconf:
    from: config.libraries.toolbox.commands.uniconf
