config:
  libraries:
    params:
      image: aroq:toolbox
      prefix: .toolbox
      tools_dir: tools
      env:
        TOOLBOX_RUN_VARIANT: true
      commands:
        test:
          params:
            cmd: toolbox
    k6:
      params:
        source: github.com/aroq/toolbox-k6
        image: aroq/toolbox-k6
      commands:
        k6:
          params:
            cmd: k6/k6
    cicd:
      params:
        source: github.com/aroq/toolbox-cicd
        image: aroq/variant-cicd
      commands:
        release:
          build:
            params:
              cmd: release/build/build
          deploy:
            params:
              cmd: release/deploy
