config:
  environments:
    dev:
      params:
        variant_config_context:
        - dev
    prod:
      params:
        variant_config_context:
        - prod

  libraries:
    params:
      variant_config_context:
      - core
      prefix: .toolbox
      tools_dir: tools
      image: aroq/toolbox
      env:
        TOOLBOX_RUN_VARIANT: true
        TOOLBOX_DOCKER_SSH_FORWARD: false
    toolbox:
      params:
        destination: toolbox
        source: github.com/aroq/toolbox//tools
      commands:
        toolbox:
          params:
            cmd: toolbox/toolbox
        template:
          params:
            cmd: toolbox/template
        uniconf:
          params:
            cmd: toolbox/uniconf
    cicd:
      params:
        destination: cicd
        source: github.com/aroq/toolbox-cicd
        image: aroq/variant-cicd
        env:
          TOOLBOX_DOCKER_SSH_FORWARD: true
      commands:
        release:
          build:
            params:
              cmd: release/build/build
          deploy:
            params:
              cmd: release/deploy
tools:
  toolbox:
    from: config.libraries.toolbox.commands.toolbox
  template:
    from: config.libraries.toolbox.commands.template
  uniconf:
    from: config.libraries.toolbox.commands.uniconf
