config:
  libraries:
    params:
      image: aroq:toolbox
      prefix: .toolbox
      tools_dir: tools
    k6:
      params:
        source: github.com/aroq/toolbox-k6
        image: aroq/toolbox-k6
      commands:
        k6:
          params:
            cmd: k6
    cicd:
      params:
        source: github.com/aroq/toolbox-cicd
        image: aroq/toolbox-cicd
      commands:
        release:
          build:
            params:
              cmd: release/build
          deploy:
            params:
              cmd: release/deploy
