config:
  libraries:
    params:
      prefix: .toolbox
      tools_dir: tools
      source: github.com/aroq/toolbox//tools
      image: aroq:toolbox
      cmd: toolbox/toolbox
      env:
        TOOLBOX_RUN_VARIANT: true
    k6:
      params:
        source: github.com/aroq/toolbox-k6
        image: aroq/toolbox-k6
      commands:
        k6:
          params:
            cmd: k6/k6
    cicd:
      params:
        source: github.com/aroq/toolbox-cicd
        image: aroq/variant-cicd
      commands:
        release:
          build:
            params:
              cmd: release/build/build
          deploy:
            params:
              cmd: release/deploy
tools:
  toolbox:
    from: config.libraries
