#!/usr/bin/env bash

# Set strict bash mode
set -euo pipefail

# Default varable values
TOOLBOX_DEPS_DIR=${TOOLBOX_DEPS_TOOLBOX_DIR:-toolbox/.toolbox/deps}

mkdir -p "${TOOLBOX_DEPS_DIR}/toolbox"

go-getter github.com/aroq/toolwrap?ref=v0.1.8 "${TOOLBOX_DEPS_DIR}/toolwrap"
go-getter github.com/aroq/toolbox-variant?ref=v0.1.2 "${TOOLBOX_DEPS_DIR}/toolbox-variant"

rsync -r --ignore-existing "${TOOLBOX_DEPS_DIR}/toolbox/templates/boilerplate/." toolbox/
